default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: karafka_aj_dev

test:
  <<: *default
  database: karafka_aj_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'karafka_aj_prod' %>
